### ISSUE TITLE
credentials should not be mandatory on UPI

### ISSUE THREAD

**Issue by ChetRHosey** [openshift/vsphere-problem-detector#37]
The credential check should not block upgrades on UPI clusters.

Unlike IPI, UPI clusters don't manage nodes. The only places I'm aware that a UPI cluster would use these credentials are for the in-tree storage drivers, and possibly for integration with NSX SDN.

Not every customer is on NSX. We don't, so we started on OpenShift SDN and moved to OVN-Kubernetes. And the in-tree storage driver is deprecated upstream and has material bugs that make it unsuitable for production use. This led us to adopt OCS.

This has worked from 4.1 -> 4.6 with no issues. Suddenly this new check has broken upgrades on 4.7. I am reluctant to start the process of getting static service credentials when we don't use NSX and Red Hat hasn't committed to fixing the bugs in the in-tree drivers.

Please make this informational on UPI clusters.

**Comment by jsafrane** [comment]
We fixed it in the recent 4.7.z release, now the problem-detector shows only an alert that you can silence and ignore.
/close
